[workspace]
package.authors = ["Philip Linden <lindenphilipj@gmail.com>"]
resolver = "2"

members = [
    "aoc-cli",
]
default-members = [
    "aoc-cli",
]

[workspace.dependencies]
glam = "0.29.0"
itertools = "0.13.0"
miette = { version = "7.4.0", features = ["fancy"] }
nom = "7.1.3"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
nom_locate = "4.2.0"
nom-supreme = "0.8.0"
test-log = { version = "0.2.13", default-features = false, features = [
    "trace",
] }
thiserror = "2.0.3"
tempfile = "3.3"
