[package]
name = "aoc-tools"
version = "0.1.0"
edition = "2021"
description = "Common tools for advent of code problems"
authors.workspace = true

[dependencies]
dotenv = "0.15"
pretty_env_logger.workspace = true
miette.workspace = true
