[package]
name = "aoc-tools"
version = "0.1.0"
edition = "2021"
description = "Common tools for advent of code problems"
authors.workspace = true

[dependencies]
nom.workspace = true
nom_supreme.workspace = true
nom_locate.workspace = true
